title: StayVisible Promotions
description: Your source for premium promotional products
url: http://localhost:4000
baseurl: ""
permalink: pretty

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Site customization
colors:
  primary: "#402195"
  secondary: "#b45e37"
  dark: "#333333"

# Contact Information
contact:
  email: info@stayvisible.com
  phone: (555) 123-4567
  address: 123 Promotion Ave, Marketing City, MC 12345 